-- Create public schemas
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: clients
CREATE TABLE public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone_number TEXT,
  instagram_handle TEXT
);

-- Table: trainers
CREATE TABLE public.trainers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  bio TEXT,
  photo_url TEXT,
  availability JSONB DEFAULT '[]'::jsonb,
  gallery JSONB DEFAULT '[]'::jsonb,
  services JSONB DEFAULT '[]'::jsonb
);

-- Table: sessions
CREATE TABLE public.sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  trainer_id BIGINT REFERENCES public.trainers(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  date TIMESTAMPTZ NOT NULL,
  service TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL DEFAULT 60,
  status TEXT NOT NULL DEFAULT 'confirmed',
  guest_name TEXT,
  guest_email TEXT
);

-- RLS setup
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trainers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Trainers: Public read, Auth users write
CREATE POLICY "Public profiles are viewable by everyone." 
  ON public.trainers FOR SELECT USING (true);
CREATE POLICY "Auth users can modify trainers." 
  ON public.trainers FOR ALL USING (auth.role() = 'authenticated');

-- Clients: Auth users full access
CREATE POLICY "Clients are viewable by authenticated users." 
  ON public.clients FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Clients can be inserted by anon users via edge func or directly if allowed." 
  ON public.clients FOR INSERT WITH CHECK (true); -- Allow insert for signups/booking
CREATE POLICY "Clients can be updated by authenticated users." 
  ON public.clients FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Clients can be deleted by authenticated users." 
  ON public.clients FOR DELETE USING (auth.role() = 'authenticated');

-- Sessions: Public read (needed for availability check?), Auth write
CREATE POLICY "Sessions are viewable by everyone (for availability)." 
  ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Sessions can be inserted by anon users." 
  ON public.sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Sessions can be modified by authenticated users." 
  ON public.sessions FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Sessions can be deleted by authenticated users." 
  ON public.sessions FOR DELETE USING (auth.role() = 'authenticated');
